/**
 * Standardized application error codes
 */
module.exports = {
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  // Module 6 Authorization Error Codes
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  FORBIDDEN_ROLE: 'FORBIDDEN_ROLE',
  TENANT_MISMATCH: 'TENANT_MISMATCH',
  CROSS_TENANT_FORBIDDEN: 'CROSS_TENANT_FORBIDDEN',
  DEPARTMENT_ACCESS_DENIED: 'DEPARTMENT_ACCESS_DENIED',
  // Module 9 Knowledge Source Error Codes
  KNOWLEDGE_SOURCE_NOT_FOUND: 'KNOWLEDGE_SOURCE_NOT_FOUND',
  DUPLICATE_KNOWLEDGE_SOURCE: 'DUPLICATE_KNOWLEDGE_SOURCE',
  INVALID_SOURCE_PATH: 'INVALID_SOURCE_PATH',
  PATH_TRAVERSAL_DETECTED: 'PATH_TRAVERSAL_DETECTED',
  UNSAFE_DIRECTORY: 'UNSAFE_DIRECTORY',
  SOURCE_SYNC_FAILED: 'SOURCE_SYNC_FAILED',
  CONNECTOR_NOT_IMPLEMENTED: 'CONNECTOR_NOT_IMPLEMENTED',
  CONFLICT: 'CONFLICT',
};
